import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import AppBar from '../comps/home/appbar'
import styles from '../styles/Home.module.css'

export default function _app({children , title}) {
    console.log(title)
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppBar />
            
            <div>
                {children}
            </div>


            <footer className={styles.footer}>
                <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                Powered by{' '}
                <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
                </a>
            </footer>
        </div>
    )
}
