import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import AppBar from '../../comps/home/appbar'
import Blog from '../../comps/home/blog'
import { makeStyles } from '@material-ui/core/styles'
import { Container, Grid } from '@material-ui/core'

const useStyles = makeStyles({
  root: {
    margin: '50px auto'
  },
  item: {
    margin: '25px auto'
  }
})

export default function Home() {
  const classes = useStyles()
  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar />
      <Container className={classes.root}>

        
        <h1 className={styles.title}>
          Detail to <a href="https://nextjs.org">Blogs!</a>
        </h1>



        
      </Container>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
