import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import AppBar from '../../comps/home/appbar'
import Link from 'next/link'
import { makeStyles } from '@material-ui/core/styles'
import { Container, Grid, Button , Box } from '@material-ui/core'

const useStyles = makeStyles({
  root: {
    margin: '50px auto'
  },
  item: {
    margin: '25px auto'
  }
})

export default function Home() {
  const classes = useStyles()
  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar />
      <Container className={classes.root}>

        
        <h1>
          Judul Blog
        </h1>
        <h4>Sabtu , 23 Agustus 2021</h4>
        <Box>
          <Image src="/blogs/thumbnail.jpg" alt="Thumbnail blog" layout="responsive" width={100} height={50} />
        </Box>
        <Box>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime, autem quia, in nobis placeat asperiores voluptas deleniti ullam repudiandae aperiam ducimus vero laboriosam molestias facere libero corrupti. Consequatur, sit dolorem!Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime, autem quia, in nobis placeat asperiores voluptas deleniti ullam repudiandae aperiam ducimus vero laboriosam molestias facere libero corrupti. Consequatur, sit dolorem!Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime, autem quia, in nobis placeat asperiores voluptas deleniti ullam repudiandae aperiam ducimus vero laboriosam molestias facere libero corrupti. Consequatur, sit dolorem!Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime, autem quia, in nobis placeat asperiores voluptas deleniti ullam repudiandae aperiam ducimus vero laboriosam molestias facere libero corrupti. Consequatur, sit dolorem!</p>
        </Box>

        <Link href="/" >
          <Button variant="contained" color="primary">
            Back Home
          </Button>
        </Link>

        
      </Container>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
